env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GITHUB_ORG=burgerit-solutions
  - DOCKER_ORG=burgerit-solutions

before:
  hooks:
    - make build-frontend

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    ids:
      - listmonk
    image_templates:
      - "ghcr.io/burgerit-solutions/lm-whg-fork:latest"
      - "ghcr.io/burgerit-solutions/lm-whg-fork:{{ .Tag }}"
    build_flag_templates:
      - --platform=linux/amd64,linux/arm64,linux/arm/v7   # Build for multiple architectures
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/BurgerIT-Solutions/lm-whg-fork
      - --label=org.opencontainers.image.source=https://github.com/BurgerIT-Solutions/lm-whg-fork
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=AGPL-3.0
    dockerfile: Dockerfile
    extra_files:
      - config.toml.sample
      - docker-entrypoint.sh

docker_manifests:
  - name_template: ghcr.io/burgerit-solutions/lm-whg-fork:latest
    image_templates:
      - ghcr.io/burgerit-solutions/lm-whg-fork:latest
    platforms:
      - linux/amd64
