name: Release

on:
  push:
    tags:
      - "v*"  # Trigger on tag push (e.g., v0.1.0)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU for multi-architecture support
        uses: docker/setup-qemu-action@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2"

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Or use another secret for GHCR auth

      - name: Prepare dependencies
        run: |
          make dist

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --parallelism 1 --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
